# Generated by Django 4.0.3 on 2022-04-08 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetails',
            name='commons_category',
            field=models.TextField(default='', verbose_name='Commons Category'),
        ),
        migrations.AlterField(
            model_name='activitydetails',
            name='address_latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00000'), max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='activitydetails',
            name='address_longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00000'), max_digits=9, verbose_name='Longitude'),
        ),
    ]
