# Generated by Django 4.0.3 on 2022-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitydetails_commons_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetails',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
