# Generated by Django 4.0.3 on 2022-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activitydetails_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetails',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
